// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJKxWfengDA2xmTPkcfbHsIEUSSMhR8kI',
    appId: '1:243406368843:web:45467cf47b1158a0e61dce',
    messagingSenderId: '243406368843',
    projectId: 'take-break-9d802',
    authDomain: 'take-break-9d802.firebaseapp.com',
    storageBucket: 'take-break-9d802.appspot.com',
    measurementId: 'G-BJNS98YDYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeodORPpmZUVwf0DIW5AZ2PgUsl77xKPk',
    appId: '1:243406368843:android:8b1a80e8352f8aa6e61dce',
    messagingSenderId: '243406368843',
    projectId: 'take-break-9d802',
    storageBucket: 'take-break-9d802.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOSZA9wDBvzQBw7JuAKppZN5xY7vrBlVc',
    appId: '1:243406368843:ios:640bb1afa2184fe3e61dce',
    messagingSenderId: '243406368843',
    projectId: 'take-break-9d802',
    storageBucket: 'take-break-9d802.appspot.com',
    iosClientId: '243406368843-uu4b32lta8qotr1gh59apvm4f9ms0a8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.takeBreak',
  );
}
